name: hydrofarm_fixed_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  syncfusion_flutter_charts: ^29.1.40
  syncfusion_flutter_datepicker: ^29.1.40
  intl: ^0.18.1
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  timezone: ^0.10.1
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5

  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  sqflite: ^2.4.1
  permission_handler: ^12.0.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
